---
web:
  hosts:
    isu1:
#    isu2:
#    isu3:
    #isu4:
    #isu5:
nginx:
  hosts:
    isu1:
#    isu2:
#    isu3:
    #isu4:
    #isu5:
db:
  hosts:
    # isu1:
    isu2:
    isu3:
    isu4:
    isu5:
redis:
  hosts:
    #isu1:
    #isu2:
    #isu3:
    #isu4:
    #isu5:
