---
- hosts: redis
  become: yes
  tasks:
    - name: redis is installed
      apt:
        name:
          - redis
        cache_valid_time: 3600
    - name: redis is started
      systemd:
        name: redis
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Copy configuration files
      copy:
        src: "../backup/{{ inventory_hostname }}{{ item }}"
        dest: "{{ item }}"
        owner: root
        group: root
        mode: 0644
      become: yes
      loop:
        - /etc/redis/redis.conf
      register: redis_config
    - name: Restart redis
      when: redis_config.changed
      become: yes
      systemd:
        name: redis
        daemon_reload: yes
        state: restarted

