---
- hosts: db
  roles:
    - name: slowquery
      become: yes
      vars:
        slowquery_database_type: mysql
        slowquery_db_user: "{{ mysql_root_user }}"
        slowquery_db_password: "{{ mysql_root_password }}"
        slowquery_threshold: "0.1"
        slowquery_enable: yes
